name: image-push-to-ECR
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # - name: Login to Amazon ECR Private
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1
      - name: Login to ecr
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ECR_ENDPOINT }}/${{ env.ECR_REPOSITORY }}
          username: ${{ secrets.ACCESS_KEY_ID }}
          password: ${{ secrets.SECRET_ACCESS_KEY }}

      # - name: Build, tag, and push docker image to Amazon ECR
      #   env:
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     REPOSITORY: blog
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
      #     docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.ECR_ENDPOINT }}/${{ env.ECR_REPOSITORY }}:latest
          file: ./Dockerfile
          cache-from: ${{ env.ECR_ENDPOINT }}/${{ env.ECR_REPOSITORY }}
